application: simpleform
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static
  static_dir: static

- url: .*
  script: simpleform.application

libraries:
- name: webapp2
  version: "2.5.2"

- name: django
  version: "1.11"
  
